# Generated by Django 5.0.4 on 2024-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=6)),
                ('Name', models.CharField(max_length=254)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=254)),
                ('Department', models.CharField(max_length=254)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=32)),
                ('Designation', models.CharField(max_length=32)),
                ('Username', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
    ]
