# Generated by Django 5.0.4 on 2024-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultymanagement', '0002_faculty_academics_faculty_development'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_academics',
            old_name='Cat_A_points_Earned',
            new_name='Cat_A_Points_Earned',
        ),
        migrations.RenameField(
            model_name='faculty_academics',
            old_name='Cat_B_points_Earned',
            new_name='Cat_B_Points_Earned',
        ),
        migrations.RenameField(
            model_name='faculty_academics',
            old_name='No_of_Actually_Held_classes',
            new_name='No_of_Actually_Held_Classes',
        ),
        migrations.RenameField(
            model_name='faculty_academics',
            old_name='No_of_Schedule_classes',
            new_name='No_of_Schedule_Classes',
        ),
        migrations.AddField(
            model_name='faculty_academics',
            name='Faculty_Id',
            field=models.CharField(default='000000', max_length=12),
        ),
    ]
