# Generated by Django 5.0.4 on 2024-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultymanagement', '0003_rename_cat_a_points_earned_faculty_academics_cat_a_points_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_development',
            name='Faculty_Id',
            field=models.CharField(default='000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='faculty_academics',
            name='Semester',
            field=models.IntegerField(),
        ),
    ]
