# Generated by Django 5.0.4 on 2024-04-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultymanagement', '0004_faculty_development_faculty_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Every_Academic_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faulty_Id', models.CharField(default='000000', max_length=12)),
                ('Faculty_Name', models.CharField(max_length=254)),
                ('Academic_Year', models.CharField(max_length=10)),
                ('Teaching_Process', models.IntegerField()),
                ('Students_Feedback', models.IntegerField()),
                ('Departmental_Activities', models.IntegerField()),
                ('Institute_Activities', models.IntegerField()),
                ('ACR', models.IntegerField()),
                ('Society_Contribution', models.IntegerField()),
                ('Total_points', models.IntegerField()),
                ('Total_points_Scale', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='faculty_academics',
            name='Result_Points',
            field=models.IntegerField(default=0),
        ),
    ]
