# Generated by Django 5.0.4 on 2024-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultymanagement', '0005_every_academic_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_academics',
            name='Semester_roman',
            field=models.CharField(default='xxx', max_length=5),
        ),
        migrations.AddField(
            model_name='faculty_development',
            name='Academics_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty_development',
            name='Semester_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty_development',
            name='Semester_Type',
            field=models.CharField(default='Odd', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty_development',
            name='Semester_roman',
            field=models.CharField(default='xxx', max_length=5),
        ),
        migrations.AlterField(
            model_name='faculty_development',
            name='Semester',
            field=models.IntegerField(default=0),
        ),
    ]
