# Generated by Django 5.0.4 on 2024-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultymanagement', '0006_faculty_academics_semester_roman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_development',
            name='Credit_Point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty_development',
            name='Verified_Status',
            field=models.CharField(default='Pending', max_length=48),
        ),
    ]
